# This file was generated by GoReleaser. DO NOT EDIT.
cask "rsecure" do
  name "rsecure"
  desc "Secure file encryption using pure Rust and AES"
  homepage "https://github.com/containerscrew/rsecure"
  version "0.3.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "rsecure"

  on_macos do
    on_intel do
      url "https://github.com/containerscrew/rsecure/releases/download/#{version}/rsecure_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/containerscrew/rsecure/"
      sha256 "21c870ef26d14b132b782cdbd859860c2c94d3ab63c684e96a4a860522ab285c"
    end
    on_arm do
      url "https://github.com/containerscrew/rsecure/releases/download/#{version}/rsecure_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/containerscrew/rsecure/"
      sha256 "9c36b107d03d6c8177ec74f2010a996e6fa7b1b368d38c67aa12fe137b75c473"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/containerscrew/rsecure/releases/download/#{version}/rsecure_#{version}_linux_amd64.tar.gz",
        verified: "github.com/containerscrew/rsecure/"
      sha256 "01d160cdb61a657c176f3c3dfaf9cb5fdf69075689120a138ba673ae5b165c31"
    end
    on_arm do
      url "https://github.com/containerscrew/rsecure/releases/download/#{version}/rsecure_#{version}_linux_arm64.tar.gz",
        verified: "github.com/containerscrew/rsecure/"
      sha256 "f3ac8567a445b3c028b28491a56d67f16c0204cc0922d4c1e7c7071b677848c1"
    end
  end

  # No zap stanza required
end
