# This file was generated by GoReleaser. DO NOT EDIT.
cask "rsecure" do
  name "rsecure"
  desc "Secure file encryption using pure Rust and AES"
  homepage "https://github.com/containerscrew/rsecure"
  version "0.4.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "rsecure"

  on_macos do
    on_intel do
      url "https://github.com/containerscrew/rsecure/releases/download/#{version}/rsecure_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/containerscrew/rsecure/"
      sha256 "d0c733a44bde782bd2a9c8dd35ddce563098201910aa71731cf39f1a05b14ca3"
    end
    on_arm do
      url "https://github.com/containerscrew/rsecure/releases/download/#{version}/rsecure_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/containerscrew/rsecure/"
      sha256 "97bc10d89a01af2c906922ec2a1943456e8f6f902713fe4acd547e7d3cda8b1d"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/containerscrew/rsecure/releases/download/#{version}/rsecure_#{version}_linux_amd64.tar.gz",
        verified: "github.com/containerscrew/rsecure/"
      sha256 "41bee200b480293a1d39bc91de0cf68bd0637b8594979ee4ea05685e24ccd7bf"
    end
    on_arm do
      url "https://github.com/containerscrew/rsecure/releases/download/#{version}/rsecure_#{version}_linux_arm64.tar.gz",
        verified: "github.com/containerscrew/rsecure/"
      sha256 "2c199ad803974bf51ce654f8584d259ae8963c372260c825a23ce54f533c491e"
    end
  end

  # No zap stanza required
end
