# This file was generated by GoReleaser. DO NOT EDIT.
cask "rsecure" do
  name "rsecure"
  desc "Secure file encryption using pure Rust and AES"
  homepage "https://github.com/containerscrew/rsecure"
  version "0.3.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "rsecure"

  on_macos do
    on_intel do
      url "https://github.com/containerscrew/rsecure/releases/download/#{version}/rsecure-darwin-amd64.tar.gz",
        verified: "github.com/containerscrew/rsecure/"
      sha256 "b2702f8598b415498192904e11f83228400b9ff0d3cf0dbeae8e233fd430f133"
    end
    on_arm do
      url "https://github.com/containerscrew/rsecure/releases/download/#{version}/rsecure-darwin-arm64.tar.gz",
        verified: "github.com/containerscrew/rsecure/"
      sha256 "80ef67ac6973581db7b3664d9bf0755deba9e37ccb632776a3a0642fbfba0662"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/containerscrew/rsecure/releases/download/#{version}/rsecure-linux-amd64.tar.gz",
        verified: "github.com/containerscrew/rsecure/"
      sha256 "4b93f6135695b237ce9ba3ae61bb8e9b44f3833b559392b04780db8e14260358"
    end
    on_arm do
      url "https://github.com/containerscrew/rsecure/releases/download/#{version}/rsecure-linux-arm64.tar.gz",
        verified: "github.com/containerscrew/rsecure/"
      sha256 "1603a494f97e9a88f944d7602cc1d0a22e8ef68c3cdafc98f71afd5d6008e0b5"
    end
  end

  # No zap stanza required
end
