# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rsecure < Formula
  desc "Secure file encryption using pure Rust and AES"
  homepage "https://github.com/containerscrew/rsecure"
  version "0.5.0"
  license "GPL-3.0-or-later"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/containerscrew/rsecure/releases/download/0.5.0/rsecure_0.5.0_darwin_amd64.tar.gz"
      sha256 "f439253c8d016328d131a2e0e65440a4d0120344fc7e4b5cee0add372e25e05b"

      define_method(:install) do
        bin.install "rsecure"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/containerscrew/rsecure/releases/download/0.5.0/rsecure_0.5.0_darwin_arm64.tar.gz"
      sha256 "ff1ab486f1185fcf9fdd53ad1693d0971c1a0b39899a9d5d65fab86c57dbea90"

      define_method(:install) do
        bin.install "rsecure"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/containerscrew/rsecure/releases/download/0.5.0/rsecure_0.5.0_linux_amd64.tar.gz"
      sha256 "acb88a7db66e2b5804e7a81bb32d6dc55a7cdd708757ff0c1270d60ac3729669"
      define_method(:install) do
        bin.install "rsecure"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/containerscrew/rsecure/releases/download/0.5.0/rsecure_0.5.0_linux_arm64.tar.gz"
      sha256 "bd1fd8fff41b1fdda20bf3466579c4cf6af96079a2da704a09fa0a240c7b64ab"
      define_method(:install) do
        bin.install "rsecure"
      end
    end
  end

  test do
    system "#{bin}/rsecure --version"
  end
end
