# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rsecure < Formula
  desc "Secure file encryption using pure Rust and AES"
  homepage "https://github.com/containerscrew/rsecure"
  version "0.8.0"
  license "GPL-3.0-or-later"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/containerscrew/rsecure/releases/download/0.8.0/rsecure_0.8.0_darwin_amd64.tar.gz"
      sha256 "c69fcee6b955bf7c7e23cc8e877274f53f6776d69a899a43107e182a7c685cb0"

      define_method(:install) do
        bin.install "rsecure"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/containerscrew/rsecure/releases/download/0.8.0/rsecure_0.8.0_darwin_arm64.tar.gz"
      sha256 "46c12cf46d57ebf8437819c688310f0af6039573e06cf4aef78db24943d952d5"

      define_method(:install) do
        bin.install "rsecure"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/containerscrew/rsecure/releases/download/0.8.0/rsecure_0.8.0_linux_amd64.tar.gz"
      sha256 "a2c9cfbf36c334275154d29502f3559374d19418b553679377c7b02b03086463"
      define_method(:install) do
        bin.install "rsecure"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/containerscrew/rsecure/releases/download/0.8.0/rsecure_0.8.0_linux_arm64.tar.gz"
      sha256 "ef7101a789af8af9b7102d71c652c27b4bb8998bcbeb1359d1a9d06d954b6413"
      define_method(:install) do
        bin.install "rsecure"
      end
    end
  end

  test do
    system "#{bin}/rsecure --version"
  end
end
